name: CD (Deploy CDK)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # needed for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: CDK synth
        run: npx cdk synth

      - name: CDK deploy (no approval)
        run: npx cdk deploy AppStack --require-approval never --outputs-file cdk-outputs.json
    
      - name: Parse API URL from outputs
        id: parseurl
        run: |
            url=$(jq -r '.AppStack.ApiUrl // empty' cdk-outputs.json)
            if [ -z "$url" ]; then
            echo "API URL not found in outputs"; exit 1
            fi
            url="${url%/}"
            echo "api_url=$url" >> "$GITHUB_OUTPUT"

      - name: OWASP ZAP Baseline scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
            target: ${{ steps.parseurl.outputs.api_url }}
            cmd_options: '-a'      # enable alpha passive checks (still quick)
            artifact_name: 'zap_report'
            fail_action: false     # keep non-blocking initially